### ISSUE TITLE
linter crashes with usage if jinja if/endif templating

### ISSUE THREAD

**Issue by mcg1969** [anaconda-distribution/anaconda-linter#138]
The following meta.yaml file causes the linter to fail. 

https://github.com/AnacondaRecipes/mlflow-feedstock/blob/3cb6b1252c9801771832e1eaf1666d97303616fa/recipe/meta.yaml

The profoundly unhelpful traceback output is below :-) It is clear to me that the use of Jinja2 if/endif blocks is at the root of the problem. I was able to bypass the issue by converting to selectors:

https://github.com/AnacondaRecipes/mlflow-feedstock/blob/b653d464904d2a84a1bf2d59661730bdb0eb83c8/recipe/meta.yaml

```
Traceback (most recent call last): File "/opt/conda/envs/linter/bin/conda-lint", line 11, in sys.exit(main()) File "/opt/conda/envs/linter/lib/python3.10/site-packages/anaconda_linter/run.py", line 92, in main result = linter.lint( File "/opt/conda/envs/linter/lib/python3.10/site-packages/anaconda_linter/lint/__init__.py", line 605, in lint msgs = self.lint_one( File "/opt/conda/envs/linter/lib/python3.10/site-packages/anaconda_linter/lint/__init__.py", line 653, in lint_one recipe = _recipe.Recipe.from_file( File "/opt/conda/envs/linter/lib/python3.10/site-packages/anaconda_linter/recipe.py", line 268, in from_file raise exc File "/opt/conda/envs/linter/lib/python3.10/site-packages/anaconda_linter/recipe.py", line 259, in from_file recipe.load_from_string(text.read(), selector_dict) File "/opt/conda/envs/linter/lib/python3.10/site-packages/anaconda_linter/recipe.py", line 207, in load_from_string self.render() File "/opt/conda/envs/linter/lib/python3.10/site-packages/anaconda_linter/recipe.py", line 403, in render self.meta = yaml.load(yaml_text) File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/main.py", line 434, in load return constructor.get_single_data() File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data node = self.composer.get_single_node() File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node document = self.compose_document() File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 99, in compose_document node = self.compose_node(None, None) File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 143, in compose_node node = self.compose_mapping_node(anchor) File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 223, in compose_mapping_node item_value = self.compose_node(node, item_key) File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 143, in compose_node node = self.compose_mapping_node(anchor) File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 216, in compose_mapping_node while not self.parser.check_event(MappingEndEvent): File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 146, in check_event self.current_event = self.state() File "/opt/conda/envs/linter/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 612, in parse_block_mapping_key raise ParserError( ruamel.yaml.parser.ParserError: while parsing a block mapping in "", line 26, column 3: number: 0 ^ (line: 26) expected , but found '' in "", line 32, column 6: -m pip install . --no-deps --ign ... ^ (line: 32)
ERROR conda.cli.main_run:execute(49): conda run conda-lint /tmp/abs_6ete_u9fte/clone failed. (See above for error)
```

**Comment by marcoesters** [comment]
Oops, I meant to assign it to Charles. I didn't mean to volunteer you @mcg1969 :-)
